services:
  caddy:
    build: .
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./etc_caddy:/etc/caddy
      - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock
        
