services:
  tracker:
    build: .
    restart: unless-stopped
    network_mode:  host
    volumes:
      - ./etc_caddy:/etc/caddy
      - ./logs:/logs
      - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock
        
